package fiji.plugin.trackmate.ctc;

import java.awt.event.WindowAdapter;

import javax.swing.JFrame;

import fiji.plugin.trackmate.Logger;
import fiji.plugin.trackmate.ctc.ui.CrawlerResultsPanel;
import fiji.plugin.trackmate.gui.Fonts;
import fiji.plugin.trackmate.gui.GuiUtils;
import fiji.plugin.trackmate.gui.Icons;
import fiji.util.gui.GenericDialogPlus;
import ij.plugin.PlugIn;

public class TrackMateParameterSweepResultsPlugin implements PlugIn
{

	@Override
	public void run( final String arg )
	{
		GuiUtils.setSystemLookAndFeel();
		final CTCResultsCrawler crawler = new CTCResultsCrawler( Logger.IJ_LOGGER );
		final String resultsFolder;
		if ( arg != null && !arg.isEmpty() )
		{
			resultsFolder = arg;
		}
		else
		{
			final GenericDialogPlus dialog = new GenericDialogPlus( "TrackMate parameter sweep results inspector" );
			dialog.setIconImage( Icons.TRACKMATE_ICON.getImage() );

			dialog.addMessage( "TrackMate parameter sweep results inspector.", Fonts.BIG_FONT );
			dialog.addMessage( "Please select a folder containing the CSV files\n"
					+ "generated by a parameter sweep." );
			dialog.addMessage( "Path to parameter sweep results folder" );
			dialog.addDirectoryField( "", System.getProperty( "user.home" ), 50 );

			dialog.showDialog();
			if ( dialog.wasCanceled() )
				return;

			resultsFolder = dialog.getNextString();
		}

		final CrawlerResultsPanel panel = new CrawlerResultsPanel( crawler );
		crawler.watch( resultsFolder );

		final JFrame frame = new JFrame( "TrackMate parameter sweep results" );
		frame.addWindowListener( new WindowAdapter()
		{
			@Override
			public void windowClosing( final java.awt.event.WindowEvent e )
			{
				crawler.stopWatching();
			}
		} );
		frame.setIconImage( Icons.TRACKMATE_ICON.getImage() );
		frame.getContentPane().add( panel );
		frame.pack();
		frame.setLocationRelativeTo( null );
		frame.setVisible( true );

	}
}
